### ISSUE TITLE
Add new clojure.string functions from Clojure 1.8

### ISSUE THREAD

**Issue by timgilbert** [zk/clojuredocs#132]
There are a few new functions in the `clojure.string` namespace in Clojure 1.8 which aren't currently covered in the [ClojureDocs documentation](https://clojuredocs.org/clojure.string). The list of new functions can be found in [CLJ-1449](http://dev.clojure.org/jira/browse/CLJ-1449) (per the 1.8 release notes).

**Comment by jafingerhut** [comment]
And in general, getting all new vars in Clojure 1.8 included on ClojureDocs.org would be nice.  There are a few outside of clojure.string namespace, too, e.g. map-entry?  Hopefully you have some code that can auto-generate the needed data from a running JVM with Clojure 1.8.

**Comment by zk** [comment]
Oh whoops, I missed the 1.8 release on the 19th. I'll update for the new vars here in a bit.

**Comment by zk** [comment]
Hey guys, just wanted to do a quick update here: bumping Clojure to 1.8 has caused issues with some of the project's dependencies. So, unfortunately, getting the new vars onto the site is not as simple as just bumping the clj version as in past updates. I'm hoping to get some time to look at this over the weekend.

**Comment by jafingerhut** [comment]
I'd encourage you to send email to the Clojure Google group with whatever dependencies you have, since several people who have had issues upgrading to Clojure 1.8 may be able to quickly recognize ones that also gave them troubles.  In particular, I recall an older version of potemkin has problems with Clojure 1.8, which led to releasing a newer version of potemkin that was compatible with 1.8.  Here are some discussion threads mentioning this:

https://groups.google.com/forum/#!searchin/clojure/1.8$20potemkin

I believe several other widely used libraries rely on potemkin, too.

**Comment by zk** [comment]
I did run into the Potemkin issue, but was able to move past it. The issue
is somewhere in the js -- best guess is that om 0.6.3 doesn't play nicely
with 1.8, but I haven't had the time to investigate fully.

If I'm still stuck after investigating I'll be sure to reach out to the
group for help.
