### ISSUE TITLE
Hitting <enter> seems to return the first result, not what you typed in

### ISSUE THREAD

**Issue by cellularmitosis** [zk/clojuredocs#205]
I keep running into this issue where I type something in, hit enter, and am brought to a page for something different than what I typed in.

It seems the page which is brought up is just whatever happens to be the top result, regardless of what you typed in.  If you typed fairly quickly, you're going to get something unexpected.

Searching for "doall", but with a slight pause after "do" seems to pretty reliably reproduce the issue:

1. type "do"
2. wait a moment for a set of results to come back
3. now quickly type "all&lt;ENTER&gt;"
4. the page which comes up is for "do", not "doall"

**Comment by bluiska** [comment]
This is an issue I have noticed myself as well. This can also happen but in a worse way in the following manner:

1. Type "u"
2 Wait a short moment and type "pdate" and hit <ENTER> immediately.
2. You will be taken to a 404 page

I believe this happens because the results start showing for "u" for which the first result is invalid. This selection remains and even though I complete typing, because I hit ENTER, the selection is not updated and instead of search results showing, I get taken to the 404 page.

**Comment by cellularmitosis** [comment]
It is interesting that this sort of issue shows up in other places around the web.  In github's web UI, when changing the base branch of a PR, if you just type in "master&lt;ENTER&gt;", it doesn't work.  You have to actually click on the "master" suggested result.

I'm trying to come up to speed with clojure, so maybe this is something I can fix!

**Comment by bluiska** [comment]
Yeah, looks like a common issue. I am quite new to Clojure myself, I had a look at the code for the searching but could not figure out where the problem lies.

To me it appears to be the issue of not updating the list and the selection quick enough.  (And the few odd cases where for example typing "u" you'll get the first result as "u#" which is not a function of course)

Have you noticed this issue was raised in 2017 as well? Just go back a few issues in the issues list, you'll find it. Seems like they don't care much about spending time fixing it.

**Comment by zk** [comment]
Dupe #174, thanks for investigating.
