### ISSUE TITLE
Automatically open function documentation if direct search is unambiquous

### ISSUE THREAD

**Issue by esuomi** [zk/clojuredocs#208]
Just noticed this while prodding around Firefox' ClojureDocs search provider:

If I search for something which only has a single result, such as [`if-let`](https://clojuredocs.org/search?q=if-let), it would be really useful to have the page automatically redirect to https://clojuredocs.org/clojure.core/if-let. This way it'd mean that when I slam `clj if-let` to my Firefox search bar, it would take me to the actual documentation page with all the nice community provided examples automatically :)

**Comment by zk** [comment]
I believe the search results page behavior would have to change so that if the query matches a function name then the user is automatically redirected to that page, which wouldn't work in the case where multiple namespaces contain the same function name.

This could be supported with a separate firefox search landing page, something to think about for future development.
