### ISSUE TITLE
Typing too fast breaks search bar

### ISSUE THREAD

**Issue by amalloy** [zk/clojuredocs#90]
I typed "->> [RET]" into the search bar, and was shown the search results for "-". I can reproduce this behavior by typing a `-` character, waiting for the search results to update, and then quickly typing `>>` followed by `Enter`.

**Comment by zk** [comment]
Took another look at this today. I fixed a bug where results can return out of order affection the quick lookup results, but otherwise it's working as intended in that the [RET] action on the search bar means 'navigate to the first autocomplete result'. The second list of results hasn't come back from the server so the first entry in the first list is navigated to.

I think the problem stems when using the quick search bar as a pure navigation tool -- a user wants to type in the name of a core var, `map`, for example, be taken to the `clojure.core/map` page.

It's worth looking into. One option is to ship all the core var names with the page cljs and fill the autocomplete results from two sources: in-mem and server.
